url: https://wsttask.github.io
site.url: https://wsttask.github.io 
timezone: Asia/Shanghai
markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge

# webrick:
#   headers:
#     Access-Control-Allow-Origin: "*"

# plugins:
#   - jekyll-feed

# collections:
#   posts:
#     permalink: /:year/:month/:day/:title/
